app:
  name: spindraad-nl
  namespace: corp-spindraad-nl # projects-<app-name> for customer projects
  domain: spindraad-nl.spindraad.app
  image:
    repository: registry.digitalocean.com/lodybo-registry/spindraad-nl
    tag: latest
