app:
  name: spindraad-nl
  namespace: corp-spindraad-nl # projects-<app-name> for customer projects
  domain: spindraad-nl.spindraad.app
  externalDomain: spindraad.nl
  image:
    repository: registry.digitalocean.com/lodybo-registry/spindraad-nl
    tag: latest
service:
  name: spindraad-nl
  port: 80
  targetPort: 3000
secrets:
    sendgridApiKey: "<PLACEHOLDER>"
