app:
  name: spindraad-nl
  namespace: corp-spindraad-nl # projects-<app-name> for customer projects
  domain: spindraad-nl.spindraad.app
  externalDomain: spindraad.nl
  devDomain: spindraad-nl.spindraad.dev
  image:
    repository: registry.digitalocean.com/lodybo-registry/spindraad-nl
    tag: latest
  domains:
    production: spindraad-nl.spindraad.app
    development: spindraad-nl.spindraad.dev
    external: spindraad.nl

environment: production # or: development

service:
  name: spindraad-nl-service
  port: 80
  targetPort: 3000

secrets:
    sendgridApiKey: "<PLACEHOLDER>"
