apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      nodeSelector:
        app-node: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secrets
                  key: SENDGRID_API_KEY
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "10m"      # 0.01 cores or 10 millicores
              memory: "128Mi"
            limits:
              cpu: "100m"     # 0.1 cores or 100 millicores
              memory: "150Mi"
          livenessProbe:
            httpGet:
              path: /healthz        # Endpoint to check
              port: {{ .Values.service.targetPort }}            # Port number of the app
            initialDelaySeconds: 10 # Time to wait before starting the probe
            periodSeconds: 10       # Interval between probes
            timeoutSeconds: 1       # Probe timeout
            failureThreshold: 3     # Restart after 3 failed probes
          readinessProbe:
            httpGet:
              path: /ready          # Endpoint that indicates readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
