apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-dns-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.domain }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
{{/*    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.app.name }}-https-redirect@kubernetescrd*/}}
    cert-manager.io/cluster-issuer: letsencrypt-dns-issuer
  labels:
    app: {{ .Values.app.name }}
spec:
  rules:
    - host: {{ .Values.app.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ .Values.app.domain }}-cert
      hosts:
        - {{ .Values.app.domain }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-dns-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.devDomain }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
{{/*    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.app.name }}-https-redirect@kubernetescrd*/}}
    cert-manager.io/cluster-issuer: letsencrypt-dns-issuer
  labels:
    app: {{ .Values.app.name }}
spec:
  rules:
    - host: {{ .Values.app.devDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ .Values.app.devDomain }}-cert
      hosts:
        - {{ .Values.app.devDomain }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-http-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http-issuer
{{/*    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.app.name }}-https-redirect@kubernetescrd*/}}
  labels:
    app: {{ .Values.app.name }}
spec:
  rules:
    - host: {{ .Values.app.externalDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
    - host: www.{{ .Values.app.externalDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ .Values.app.externalDomain }}-cert
      hosts:
        - {{ .Values.app.externalDomain }}
        - www.{{ .Values.app.externalDomain }}
---
{{/*apiVersion: traefik.io/v1alpha1*/}}
{{/*kind: Middleware*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.app.name }}-https-redirect*/}}
{{/*  namespace: {{ .Values.app.namespace }}*/}}
{{/*spec:*/}}
{{/*  redirectScheme:*/}}
{{/*    scheme: https*/}}
{{/*    permanent: true*/}}
