apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.app.name }}-https-redirect
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    managed-by: helm
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.app.name }}-robots-deny
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    managed-by: helm
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow, nosnippet, noarchive"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-dns-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    {{- if eq .Values.environment "production" }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.domains.production }}
    {{- else if eq .Values.environment "development" }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.domains.development }}
    {{- end }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.app.namespace }}-{{ .Values.app.name }}-https-redirect@kubernetescrd,{{ .Values.app.namespace }}-{{ .Values.app.name }}-robots-deny@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-dns-issuer
  labels:
    app: {{ .Values.app.name }}
spec:
  rules:
    {{- if eq .Values.environment "production" }}
    - host: {{ .Values.app.domains.production }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
    {{- else if eq .Values.environment "development" }}
    - host: {{ .Values.app.domains.development }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
  tls:
    {{- if eq .Values.environment "production" }}
    - secretName: {{ .Values.app.domains.production }}-cert
      hosts:
        - {{ .Values.app.domains.production }}
        {{- else if eq .Values.environment "development" }}
    - secretName: {{ .Values.app.domains.development }}-cert
      hosts:
        - {{ .Values.app.domains.development }}
        {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-external-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http-issuer
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.externalDomain }},www.{{ .Values.app.externalDomain }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.app.namespace }}-{{ .Values.app.name }}-https-redirect@kubernetescrd
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment }}
    managed-by: helm
spec:
  rules:
    - host: {{ .Values.app.externalDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
    - host: www.{{ .Values.app.externalDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ .Values.app.externalDomain }}-cert
      hosts:
        - {{ .Values.app.externalDomain }}
        - www.{{ .Values.app.externalDomain }}
