apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SENDGRID_API_KEY: {{ .Values.secrets.sendgridApiKey | b64enc | quote }}
