apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    {{-if eq .Values.environment "production" }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.domain }}
    {{- else if eq .Values.environment "development" }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.domains.development }}
    {{- end }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
